name: oureye
description: AI-powered visual assistant app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Camera
  camera: ^0.10.5+5
  
  # Permissions
  permission_handler: ^11.0.1
  
  # HTTP requests
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Speech to Text
  speech_to_text: ^7.3.0
  
  # Text to Speech
  flutter_tts: ^3.8.5

  flutter_svg: ^2.0.9
  
  # Audio player for sound effects
  audioplayers: ^5.2.1
  
  # Path provider
  path_provider: ^2.1.1
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_generative_ai: ^0.4.7
  
  # Database
  postgres: ^2.6.2
  
  # Security
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/images/